#NOT NEEDED
#apiVersion: apps/v1
#kind: StatefulSet
#metadata:
#  name: auth-mongo-deployment
#  labels:
#    app: auth-mongo
#spec:
#  replicas: 1
#  serviceName: 'auth-mongo'
#  selector:
#    matchLabels:
#      app: auth-mongo
#  template:
#    metadata:
#      labels:
#        app: auth-mongo
#    spec:
#      volumes:
#        - name: auth-mongo-storage
#          persistentVolumeClaim:
#            claimName: auth-db-bs-claim
#      containers:
#        - name: auth-mongo
#          image: mongo
#          volumeMounts:
#            - mountPath: '/data/db'
#              name: auth-mongo-storage
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: auth-mongo-srv
#spec:
#  type: ClusterIP
#  selector:
#    app: auth-mongo
#  ports:
#    - name: db
#      protocol: TCP
#      port: 27017
#      targetPort: 27017
#
##apiVersion: apps/v1
##kind: StatefulSet
##metadata:
##  name: auth-mongo-deployment
##  labels:
##    app: auth-mongo
##spec:
##  replicas: 1
##  selector:
##    matchLabels:
##      app: auth-mongo
##  template:
##    metadata:
##      labels:
##        app: auth-mongo
##    spec:
##      containers:
##        - name: auth-mongo
##          image: mongo
##---
##apiVersion: v1
##kind: Service
##metadata:
##  name: auth-mongo-svc
##spec:
##  selector:
##    app: auth-mongo
##  ports:
##    - name: db
##      protocol: TCP
##      port: 27017
##      targetPort: 27017
#
