#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: auth-db-bs-claim-many
#spec:
#  storageClassName: auth-db-bs-claim
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 200Mi
#
#NOT NEEDED
#kind: PersistentVolume
#apiVersion: v1
#metadata:
#  name: auth-many-v-2
#  labels:
#    type: local
#    app: auth-mongo
#  hostPath:
#    path: "/data/db"
#spec:
#  storageClassName: manual
#  capacity:
#    storage: 5Gi
#  accessModes:
#    - ReadWriteMany
#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: postgres-pv-claim
#spec:
#  storageClassName: manual
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 5Gi